openapi: 3.0.1
info:
  title: Star Wars
  description: ''
  version: '1.0'
servers:
  - url: https://apim-osk-apiops-dev-001.azure-api.net/starwars
paths:
  /people:
    get:
      summary: Get People
      operationId: get-people
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]